### PR TITLE
Properly handle dashes in the mediaIds

### PR DESCRIPTION
**Pull request by ronaldewatts**
This is a fix for https://github.com/Azure/azure-documentdb-node/issues/81 in which a dash (-) was being converted to a plus (+) in the base64 conversion and the resulting attachmentId would be incorrect

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ronaldewatts__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by ronaldewatts** [comment]
I needed to update this PR with another commit to globally replace the - before base64 conversion.

**Comment by ronaldewatts** [comment]
I see this is still unassigned.  Has anybody had a chance to review it?  I know that the sdk version has now been updated to 1.5 but I'm stuck on a fork of 1.4 as this issue is quite disruptive.  I'm surprised nobody else has ran into it unless nobody else is piping attachments through in NodeJS.

**Comment by ato9000** [comment]
Hi,

Could you please add a unit test for this change.

--Armando

**Comment by ronaldewatts** [comment]
@ato9000 I added tests to the `baseTests.js` file.  Let me know if you there is more to add.  Thanks!

**Comment by ronaldewatts** [comment]
Also, as a note this same issue would exist in the client-side JS library as well.  https://github.com/Azure/azure-documentdb-js/blob/master/documentdbclient-1.4.0.js#L307

**Comment by ryancrawcour** [comment]
Thx @ronaldewatts we'll take a look at your tests and verify shortly

**Comment by ryancrawcour** [comment]
Yes, the JS client SDK will have the same issue, it is generated from the Node.js code

**Comment by ato9000** [comment]
Valid mediaIds have to have a length of 20 or 21. Please update the last test to be 20 characters long (as opposed to less than 20).

Thanks,
Armando

**Comment by ato9000** [comment]
On second thought, I'll accept the PR and fix the test when I add the corresponding check for length of mediaId

**Comment by ronaldewatts** [comment]
Thank you @ato9000 .  Do you know the schedule for getting this into the next version?

**Comment by ryancrawcour** [comment]
We're about to push to npm now

**Pull request merged**
