### PR TITLE
Return headers for all query requests

### PR DESCRIPTION
**Pull request by markusahlstrand**
The aim for this PR is to return an array of all the headers returned from docDb for the current request. It could be that it would be better to extract information, such as the sum of the request charge, but I first wanted to check if I'm on the right track.

There are a couple of requests which isn't tracked in this version, such as the request for partitions and the query-rewrite responses from the server, but as far as I understand it there's no request charge for these requests?

This is a new code-base for me so I could be missing some changes to some of the other execution contexts? So far I only checked that it worked in my particular use-case which is a cross-partition query.

This PR is for Issue #146.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@markusahlstrand__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by markusahlstrand** [comment]
Hi @rnagpal,

It would be great with some feedback so that we could get this issue fixed. Do you know when anyone might have time to review this PR to see if it's on the right track and which kind of data we should return to the user?

Cheers,
Markus

**Comment by markusahlstrand** [comment]
Hi @moderakh and @rnagpal,

Is there any progress on reviewing this PR? Really need this to be able to track the usage and would like to avoid running my own fork in production if I don't have to.

/Markus

**Comment by moderakh** [comment]
@markusahlstrand 
Thank you for your PR.  I think `executeNext` is more suitable for returning the headers because it returns the next page of result and the corresponding header response. 

If we return all the header responses in `toArray`, it is not clear which results associate to which header response.

Why aren't you using `executeNext` instead?

**Comment by moderakh** [comment]
Also there is no charge for getting the query plan (including rewritten query) in parallel for partitioned collection.

**Comment by markusahlstrand** [comment]
Thanks for the feedback! I don't yet have a complete understanding of the code base so it could well be a better solution. I'll have a look at it.

**Comment by DDeme** [comment]
Status of this issue ? I need this.

**Comment by markusahlstrand** [comment]
It's kind of fixed. If you use a query iterator you get the headers back, but only if the query returns an items. Opened a new issue for this: https://github.com/Azure/azure-documentdb-node/issues/207

**Comment by moderakh** [comment]
We are returning request charge for all queries including cross partition query. 
If you want to access headers request charge you should use `queryIterator.executeNext(callback(err, resources, headers))` api. request charge in headers should always be populated for any query.

Please see this https://github.com/Azure/azure-documentdb-node/issues/207#event-1312317246

**Pull request closed without merging**
