### PR TITLE
Clean up socket timeout listener

### LINKED ISSUE #95: EventEmitter listener leak warning
```
(node) warning: possible EventEmitter memory leak detected. 11 timeout listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:665:33)
    at ClientRequest.<anonymous> (...node_modules/documentdb/lib/request.js:95:16)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:496:7)
    at onSocketNT (_http_client.js:508:5)
    at nextTickCallbackWith2Args (node.js:474:9)
    at process._tickCallback (node.js:388:17)
```

Looking at [the code](https://github.com/Azure/azure-documentdb-node/blob/master/source/lib/request.js#L95) it definitely looks like there is a problem. Since [keepalive](https://github.com/Azure/azure-documentdb-node/blob/master/source/lib/request.js#L37) is used, the `timeout` event will be listened to several times on the same socket.

### PR DESCRIPTION
**Pull request by joaomoreno**
This PR fixes #95.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@joaomoreno__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by ryancrawcour** [comment]
Could you please add some tests for this PR. Thanks.

**Comment by joaomoreno** [comment]
Blocked by #97

**Comment by claudio-destro-banzai** [comment]
Hi, Same issue here.
BTW I used joaomoreno patch and seems ok.
Don't know if it is related, but the patch seems to solve even many "Request rate" exceptions.

**Comment by ryancrawcour** [comment]
@claudio-destro-banzai thanks for verifying that the fix works. we will merge this and distribute a new version to npm asap.

**Comment by claudio-destro-banzai** [comment]
great, thank you!

**Pull request merged**
