### PR TITLE
Fixes issue #107 (continuation token handling)

### PR DESCRIPTION
**Pull request by stefan-akelius**
This PR fixes the faulty continuation token handling described in [Issue #107](https://github.com/Azure/azure-documentdb-node/issues/107).

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@stefan-akelius__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by rnagpal** [comment]
@moderakh will be looking into this and merging.
@stefan-akelius:  Could you also add a unit test as part of this PR?

**Comment by stefan-akelius** [comment]
@rnagpal I'd like to, but I couldn't get the tests running on my Mac. I don't have Windows.

**Comment by rnagpal** [comment]
@stefan-akelius Do you mean that we have a Windows dependency for running Node.js tests? Can you tell us what's the error you are getting while trying to run the tests on your Mac?

**Comment by Bomret** [comment]
Writing from my private account.

I followed the instructions in `source/test/readme.md` and redirected the output to a file that I attached [here](https://github.com/Azure/azure-documentdb-node/files/711964/docdb-test.txt). There are some successful tests but also many failed ones that say something about `ECONNREFUSED`. Is there maybe a dependency to the local DocumentDB emulator that is only available on Windows, yet?

**Comment by Bomret** [comment]
I took a look and found that some tests try to connect to a DocumentDB account that has to be configured via `_testConfig.json`. Since the DocumentDB emulator just runs on Windows and the functions used in the tests seem to cost money when fired against an Azure DocumentDB account, I can't execute all tests. But I can add some that just make sure the continuation token is properly used inside the [defaultQueryExecutionContext.js](https://github.com/Azure/azure-documentdb-node/blob/master/source/lib/queryExecutionContext/defaultQueryExecutionContext.js).

**Comment by stefan-akelius** [comment]
@rnagpal I pushed some tests for this issue that I could also run on my Mac. As it seems there are no explicit tests for any of the code inside the `queryExecutionContext` directory?

**Comment by rnagpal** [comment]
@stefan-akelius Sorry for the delay here. I'm going to review the PR and make appropriate changes(if needed) and merge as soon as possible.

**Comment by stefan-akelius** [comment]
Is there any eta on this?

**Comment by rnagpal** [comment]
@stefan-akelius @moderakh will start working on it this week and we should release an update to the SDK soon.

**Comment by moderakh** [comment]
Hi @stefan-akelius 
Thanks for your contribution. I think your PR should work for single collection partition (supporting continuation token for partitioned-collection is more difficult and we will do it internally.) Could you please also add an end-to-end integration test for continuation token in single partition collection scenario? 

`test.js` and `orderByTests.js` are two examples of end to end tests.

**Comment by stefan-akelius** [comment]
@moderakh will do asap (this week)

**Comment by khdang** [comment]
@stefan-akelius I've added the end-to-end tests, could you please take a look and merge it so we can finalize this PR?

**Comment by Bomret** [comment]
@khdang got piled with work and didn't came around doing it. Your tests look good for me 👍

**Comment by khdang** [comment]
@Bomret Thanks!

**Comment by moderakh** [comment]
Thank you @Bomret and @khdang

**Comment by MatejSkrbis** [comment]
@khdang Can I ask why did you change the fix from @Bomret. I tried his fix and it worked, but you have taken continuation from this.options instead of options which make it fails. I don't know how did you write the unit tests as trying it out does not work.

Can this be changed back to @Bomret solution?

**Comment by khdang** [comment]
@MatejSkrbis  The change I made was just refactoring and shouldn't change the behavior of Bomret's fix. Could you provide sample code that does not work for you? If it's an issue we can fix to a working solution.

**Comment by MatejSkrbis** [comment]
@khdang The change that @Bomret made to `defaultQueryExecutionContext.js` was changing
`this.continuation = null;`
to
`this.continuation = options ? options.continuation : null;`

and you changed his code to
`this.continuation = this.options.continuation || null;`

The problem here is that variable `options` got the continuation token, while `this.options` is `undefined `and does not. So you introduced a bug instead of a fix.

**Comment by khdang** [comment]
@MatejSkrbis I also moved that line after the assignment of this.options = options ? null so this.options has the value of options when it gets to the assignment of continuation. Does that make sense?

**Comment by MatejSkrbis** [comment]
@khdang yes that makes sense, I made a mistake. Thank you for quick response and sorry that I took your precious time. I thought that if I would do `npm install` on latest package that the newest change would be inside. Because it wasn't I changed only this line, but haven't noticed that you moved the line. Sorry again and thank you for explanation.

**Comment by khdang** [comment]
@MatejSkrbis No problem, you're welcome.

**Pull request merged**
