### PR TITLE
Added Promises.  Use of callbacks still supported.

### PR DESCRIPTION
**Pull request by MarkMYoung**
Inspired by #185.  I ran MochaJS tests according the the readme without any errors.  However, MochaJS is new to me and I don't contribute forks very often so I need some peer review.

### CODE REVIEW

**Comment by ronenteva** [comment]
Hope this will get merged! Thanks @MarkMYoung

**Comment by coreyperkins** [comment]
Somebody merge this!!!

**Comment by SimonSchick** [comment]
Hey, our team wants to use this soon, any chance this can be merged?

**Comment by DDeme** [comment]
Can you please merge these feature ?  What needs to be done to get it merged  ?

**Comment by aaronjameslang** [comment]
Can somebody please confirm this change is welcome?

Happy to bring this up to date if it's going to get merged.

**Comment by moderakh** [comment]
@christopheranderson can you please respond on this.

**Comment by christopheranderson** [comment]
Promises are now supported in the TypeScript-ified version of the SDK: https://github.com/Azure/azure-cosmos-js

We decided to do the Promise support alongside of the TypeScript conversion because "async" makes the promises a bit more natural. 

I'm going to close this now, but please know I appreciate the work that went into this PR. If it wasn't for the awesomeness that TypeScript brings, this would have been the right approach for sure.

**Comment by aaronjameslang** [comment]
Thanks for the update @christopheranderson 😄 

Will this repo/module be deprecated once `@azure/cosmos` is ready?

When can we expect `@azure/cosmos` to be released? 1/3/6/12 months?

**Pull request closed without merging**
